# config file version
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: 1d223ca15b2e42e1b1659662ef455b93
    jsonData:
      version: Flux
      organization: opi
      defaultBucket: opi
      tlsSkipVerify: true
