version: "3.9"

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.48.0
    command:
      - "--config=/etc/otel-collector-config.yml"
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55670:55679" # zpages extension
      - "54525:54525" # tcp log receiver
    depends_on:
      - influxdb
    networks:
      - opi

  grafana:
    image: grafana/grafana:8.4.6
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
    networks:
      - opi

  influxdb:
    image: influxdb:2.2.0-alpine
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=opi
      - DOCKER_INFLUXDB_INIT_PASSWORD=opi123456789
      - DOCKER_INFLUXDB_INIT_ORG=opi
      - DOCKER_INFLUXDB_INIT_BUCKET=opi
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=1d223ca15b2e42e1b1659662ef455b93
    networks:
      - opi

volumes:
  influxdb-storage:

networks:
  opi:

