name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths:
      - 'examples/telegraf/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/telegraf/**'

  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Start containers
        run: docker-compose -f "docker-compose.yml" up --detach --build
        working-directory: examples/telegraf

      - name: Run tests
        run: |
          echo wait 5s for SPDK to start... && sleep 5s
          docker-compose logs
          docker-compose ps
          docker inspect --format='{{json .Name}} - {{json .State.Health.Status}}' $(docker-compose ps -q)
          uniq -c <<< $(docker inspect --format='{{json .State.Health.Status}}' $(docker-compose ps -q)) | grep -q '4 "healthy"' || true
          docker-compose exec -T spdk /usr/local/bin/perf -r 'traddr:127.0.0.1 trtype:TCP adrfam:IPv4 trsvcid:4420' -c 0x1 -q 1 -o 4096 -w randread -t 10 || true
        working-directory: examples/telegraf

      - name: Logs
        if: failure()
        run: |
          docker-compose ps || true
          docker-compose logs || true
        working-directory: examples/telegraf

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
        working-directory: examples/telegraf
