---
name: 'OPI SZTP CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'examples/sztp/**'
      - '.github/workflows/sztp.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/sztp/**'
      - '.github/workflows/sztp.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: sztp-${{ github.ref }}
  cancel-in-progress: true

jobs:

  sztp-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Start containers
      run: docker-compose up -d
      working-directory: examples/sztp

    - name: Run Tests
      run: ./tests.sh
      working-directory: examples/sztp

    - name: Logs
      if: failure()
      run: docker-compose logs
      working-directory: examples/sztp

    - name: Stop containers
      if: always()
      run: docker-compose down
      working-directory: examples/sztp
